# Generated by Django 5.2.5 on 2025-10-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
