# Generated by Django 5.2.5 on 2025-12-05 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenuereport',
            options={'ordering': ['-report_date']},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='service_order',
        ),
        migrations.RemoveField(
            model_name='revenuereport',
            name='total_service_orders',
        ),
        migrations.AddField(
            model_name='revenuereport',
            name='average_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='revenuereport',
            name='revenue_per_available_room',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='revenuereport',
            name='total_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revenuereport',
            name='total_nights',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_nights', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('tier', models.CharField(choices=[('bronze', 'Đồng'), ('silver', 'Bạc'), ('gold', 'Vàng'), ('platinum', 'Bạch Kim')], default='bronze', max_length=20)),
                ('first_booking_date', models.DateTimeField(blank=True, null=True)),
                ('last_booking_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='customers.customer')),
            ],
        ),
    ]
