# Generated by Django 4.2.7 on 2025-12-05 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revenue', '0002_alter_revenuereport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloyalty',
            name='customer',
            field=models.OneToOneField(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to=settings.AUTH_USER_MODEL),
        ),
    ]
