# Generated by Django 5.2.5 on 2025-12-04 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_booking_created_by'),
        ('services', '0002_alter_serviceorder_assigned_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category__sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AddField(
            model_name='service',
            name='preparation_time',
            field=models.IntegerField(default=15, help_text='Thời gian chuẩn bị (phút)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(default='star', help_text='Icon class name', max_length=50),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.CharField(blank=True, help_text='URL hình ảnh', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.CharField(default='món', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['employee', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_orders_old', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['employee', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_orders_old', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RoomServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('partial', 'Thanh toán một phần')], default='unpaid', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị'), ('ready', 'Sẵn sàng'), ('delivered', 'Đã giao'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_employee', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['employee', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_orders', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.booking')),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['employee', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú đặc biệt cho món này')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.roomserviceorder')),
            ],
        ),
    ]
